services:
  web:
    image: php:8.1-fpm
    container_name: php-app
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-app
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - web
    networks:
      - app-network

  sass:
    image: node:16-alpine
    container_name: sass-compiler
    working_dir: /var/www/html
    command: sh -c "npm install && npm run sass"
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
